version: "3.9"

services:

  kafka-0:
    networks:
      kafka-net:
        ipv4_address: 172.28.1.1
    image: docker.io/bitnami/kafka:3.5.1-debian-11-r1
    ports:
      - 9094:9094
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@172.28.1.1:9093,1@172.28.1.2:9093,2@172.28.1.3:9093
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092,EXTERNAL://172.28.1.1:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
#      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=2
#      - KAFKA_CFG_OFFETS_TOPIC_REPLICATION_FACTOR=2
#      - KAFKA_CFG_NUM_PARTITIONS=3
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    volumes:
      - kafka_0:/bitnami/kafka

  kafka-1:
    networks:
      kafka-net:
        ipv4_address: 172.28.1.2
    image: docker.io/bitnami/kafka:3.5.1-debian-11-r1
    ports:
      - 9092
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@172.28.1.1:9093,1@172.28.1.2:9093,2@172.28.1.3:9093
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092,EXTERNAL://172.28.1.1:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
#      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=2
#      - KAFKA_CFG_OFFETS_TOPIC_REPLICATION_FACTOR=2
#      - KAFKA_CFG_NUM_PARTITIONS=3
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    volumes:
      - kafka_1:/bitnami/kafka

  kafka-2:
    networks:
      kafka-net:
        ipv4_address: 172.28.1.3
    image: docker.io/bitnami/kafka:3.5.1-debian-11-r1
    ports:
      - 9092
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@172.28.1.1:9093,1@172.28.1.2:9093,2@172.28.1.3:9093
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092,EXTERNAL://172.28.1.1:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
#      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=2
#      - KAFKA_CFG_OFFETS_TOPIC_REPLICATION_FACTOR=2
#      - KAFKA_CFG_NUM_PARTITIONS=3
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    volumes:
      - kafka_2:/bitnami/kafka

  kafka-ui:
    depends_on:
      - kafka-0
      - kafka-1
      - kafka-2
    networks:
      kafka-net:
        ipv4_address: 172.28.1.4
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 3000:8080
    volumes:
      - ./config/kui-config-cluster.yml:/etc/kafkaui/dynamic_config.yaml
    environment:
      - DYNAMIC_CONFIG_ENABLED=true

  minio:
    restart: on-failure
    networks:
      kafka-net:
        ipv4_address: 172.28.1.5
    image: bitnami/minio:2023.7.18-debian-11-r2
    ports:
      - 3002:9001
    volumes:
      - minio:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=abc123456
      - MINIO_DEFAULT_BUCKETS=diff-data

networks:

  kafka-net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

volumes:

  kafka_0:
    driver: local
  kafka_1:
    driver: local
  kafka_2:
    driver: local
  minio:
    driver: local
